LMSWeb/Controllers/LessonController.cs
using LMS.DataAccess.Repository.IRepository;
using LMS.Models;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json.Serialization;
using System.Text.Json;
using LMS.Models.ViewModels;
using Microsoft.AspNetCore.Hosting;

namespace LMSWeb.Controllers
{
    public class LessonController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public LessonController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult GetLesson(int lessonId)
        {
            var lesson = _unitOfWork.Lesson.Get(u => u.LessonId == lessonId);
            if (lesson != null)
            {
                lesson.Contents = _unitOfWork.Content.GetAllWithExp(u => u.LessonId == lessonId).ToList();
                var curUserId = Convert.ToInt32(User.Claims.FirstOrDefault(c => c.Type == "id").Value);
                lesson.UserLessonProgresses = _unitOfWork.UserLessonProgress.GetAllWithExp(u => u.LessonId == lessonId && u.UserId == curUserId).ToList();
                var jsonOptions = new JsonSerializerOptions
                {
                    ReferenceHandler = ReferenceHandler.Preserve
                };

                // Serialize the lesson and return it as JSON
                var lessonJson = JsonSerializer.Serialize(lesson, jsonOptions);
                return Content(lessonJson, "application/json");
            }
            else
            {
                return NotFound(); // Handle the case where the lesson is not found
            }

        }

        public IActionResult Upsert(int courseId, int? id)
        {
            LessonVM lessonVM = new()
            {
                Lesson = new Lesson()
            };
            if (id == null || id == 0)
            {
                lessonVM.Lesson.CourseId = courseId;
                return View(lessonVM);
            }
            else
            {
                //update
                lessonVM.Lesson = _unitOfWork.Lesson.Get(u => u.LessonId == id);
                return View(lessonVM);
            }
        }

        [HttpPost]
        public IActionResult Upsert(LessonVM lessonVM)
        {
            lessonVM.Lesson.Course = _unitOfWork.Course.Get(u => u.CourseId == lessonVM.Lesson.CourseId); //for now manually assigned at the view
            if (ModelState.IsValid) // User field is intentionally nullable for now can't solve the ModelState.IsValid - User field is required problem
            {

                if (lessonVM.Lesson.LessonId == 0)
                {
                    _unitOfWork.Lesson.Add(lessonVM.Lesson);
                    _unitOfWork.Save();
                    int newAddedLessonId = lessonVM.Lesson.LessonId;
                    var enrolledUsers = _unitOfWork.User.GetAllWithExp(u => u.Enrollments.Any(e => e.CourseId == lessonVM.Lesson.CourseId));
                    foreach (var user in enrolledUsers)
                    {
                        UserLessonProgress ulProgress = new UserLessonProgress()
                        {
                            UserId = user.UserId,
                            LessonId = newAddedLessonId,
                            IsCompleted = false
                        };
                        _unitOfWork.UserLessonProgress.Add(ulProgress);
                        _unitOfWork.Save();
                    }
                    //Bu kurstaki bu ders için her enrollment başına userlessonprogress oluşturup iscompletedi false çek.
                }
                else
                {
                    //TO-DO implement Update in Lesson repo
                }


                TempData["success"] = "Lesson created successfully";
                return RedirectToAction("Details", "Course", new { courseId = lessonVM.Lesson.CourseId });
            }
            else
            {
                return View(lessonVM);
            }
        }

        public IActionResult Delete(int lessonId)
        {
            LessonVM lessonVM = new()
            {
                Lesson = _unitOfWork.Lesson.Get(u => u.LessonId == lessonId)
            };
            return View(lessonVM);
        }

        [HttpPost]
        public IActionResult Delete(LessonVM lessonVM)
        {
            if (ModelState.IsValid) // User field is intentionally nullable for now can't solve the ModelState.IsValid - User field is required problem
            {
                var ulProgresses = _unitOfWork.UserLessonProgress.GetAllWithExp(ulp => ulp.LessonId == lessonVM.Lesson.LessonId);
                foreach (var ulp in ulProgresses)
                {
                    _unitOfWork.UserLessonProgress.Remove(ulp);
                }
                _unitOfWork.Lesson.Remove(lessonVM.Lesson);
                _unitOfWork.Save();

                TempData["success"] = "Lesson removed successfully";
                return RedirectToAction("Details", "Course", new { courseId = lessonVM.Lesson.CourseId });
            }
            else
            {
                return View(lessonVM);
            }
        }

        [HttpPost]
        public IActionResult CompleteLesson(int lessonId)
        {
            try
            {
                // Retrieve the lesson from the database
                var lesson = _unitOfWork.Lesson.Get(l => l.LessonId == lessonId);

                if (lesson == null)
                {
                    return NotFound(); // Lesson not found
                }

                // Check if the user has already completed the lesson
                var curUserId = Convert.ToInt32(User.Claims.FirstOrDefault(c => c.Type == "id").Value);
                var user = _unitOfWork.User.Get(u => u.UserId == curUserId); // Implement GetUserId() to get the current user's ID
                if (user == null)
                {
                    return Unauthorized(); // User not authenticated
                }

                var userLessonProgress = _unitOfWork.UserLessonProgress.Get(ulp =>
                    ulp.LessonId == lessonId && ulp.UserId == user.UserId);

                if (userLessonProgress != null && userLessonProgress.IsCompleted)
                {
                    return Conflict(); // Lesson already completed by the user
                }

                // Mark the lesson as completed for the user
                if (userLessonProgress == null)
                {
                    userLessonProgress = new UserLessonProgress
                    {
                        UserId = user.UserId,
                        LessonId = lessonId,
                        IsCompleted = true
                    };
                    _unitOfWork.UserLessonProgress.Add(userLessonProgress);
                }
                else
                {
                    userLessonProgress.IsCompleted = true;
                    _unitOfWork.UserLessonProgress.Update(userLessonProgress);
                }

                _unitOfWork.Save(); // Save changes to the database

                return Ok(); // Lesson marked as completed successfully
            }
            catch (Exception ex)
            {
                // Log the exception or handle it as needed
                return StatusCode(500); // Internal server error
            }
        }





        //private readonly IUnitOfWork _unitOfWork;
        //private readonly IWebHostEnvironment _webHostEnvironment;
        //public LessonController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        //{
        //    _unitOfWork = unitOfWork;
        //    _webHostEnvironment = webHostEnvironment;
        //}
        //public IActionResult GetLesson(int lessonId)
        //{
        //    var lesson = _unitOfWork.Lesson.Get(u => u.LessonId == lessonId);
        //    if (lesson != null)
        //    {
        //        lesson.Contents = _unitOfWork.Content.GetAllWithExp(u => u.LessonId == lessonId).ToList();
        //        var jsonOptions = new JsonSerializerOptions
        //        {
        //            ReferenceHandler = ReferenceHandler.Preserve
        //        };

        //        // Serialize the lesson and return it as JSON
        //        var lessonJson = JsonSerializer.Serialize(lesson, jsonOptions);
        //        return Content(lessonJson, "application/json");
        //    }
        //    else
        //    {
        //        return NotFound(); // Handle the case where the lesson is not found
        //    }

        //}

        //public IActionResult Upsert(int courseId, int? id)
        //{
        //    LessonVM lessonVM = new()
        //    {
        //        Lesson = new Lesson()
        //    };
        //    if (id == null || id == 0)
        //    {
        //        lessonVM.Lesson.CourseId = courseId;
        //        return View(lessonVM);
        //    }
        //    else
        //    {
        //        //update
        //        lessonVM.Lesson = _unitOfWork.Lesson.Get(u => u.LessonId == id);
        //        return View(lessonVM);
        //    }
        //}

        //[HttpPost]
        //public IActionResult Upsert(LessonVM lessonVM)
        //{
        //    lessonVM.Lesson.Course = _unitOfWork.Course.Get(u => u.CourseId == lessonVM.Lesson.CourseId); //for now manually assigned at the view
        //    if (ModelState.IsValid) // User field is intentionally nullable for now can't solve the ModelState.IsValid - User field is required problem
        //    {

        //        if (lessonVM.Lesson.LessonId == 0)
        //        {
        //            _unitOfWork.Lesson.Add(lessonVM.Lesson);
        //        }
        //        else
        //        {
        //            //TO-DO implement Update in Lesson repo
        //        }

        //        _unitOfWork.Save();

LMSWeb/Views/Course/Details.cshtml
@model Course

<div class="container mt-4">
    <div class="row">
        <div class="col-md-6">
            <img src="@Model.ImageUrl" class="img-fluid rounded" alt="Course Image" />
        </div>
        <div class="col-md-6">
            <h2>@Model.Title</h2>
            <p>By: @Model.User.Name</p>
            <p>@Model.Description</p>
            <p>Enrollment Count: @Model.EnrollmentCount</p>

            <!-- Add any other course details you want to display here -->
            @if (User.Identity.IsAuthenticated)
            {
                @if (ViewBag.IsEnrolled != null)
                {
                    <button type="submit" class="btn btn-primary" disabled>Already Enrolled</button>
                }
                else
                {
                    <form method="post" asp-controller="Course" asp-action="Enroll" asp-route-courseId="@Model.CourseId"
                          asp-route-userId="@Convert.ToInt32(User.Claims.FirstOrDefault(c => c.Type == "id")?.Value)">
                        <button type="submit" class="btn btn-primary">Enroll in Course</button>
                    </form>
                }

            }
            <a asp-controller="Course" asp-action="Edit" asp-route-courseId="@Model.CourseId" class="flex-shrink-0 btn btn-sm btn-primary px-3 border-end" style="border-radius: 30px 0 0 30px;">Course Content</a>

            @if (((User.Identity.IsAuthenticated) && (((((User.Claims.FirstOrDefault(c => c.Type == "role").Value.Equals("Instructor")))) && ((Convert.ToInt32(User.Claims.FirstOrDefault(c => c.Type == "id").Value)) == Model.UserId)) ||
            User.Claims.FirstOrDefault(c => c.Type == "role").Value.Equals("Admin"))))
            {
                <a asp-controller="Course" asp-action="EnrolledUsers" asp-route-courseId="@Model.CourseId" class="flex-shrink-0 btn btn-sm btn-primary px-3 border-end" style="border-radius: 30px 0 0 30px;">See Enrolled Users</a>
                <a asp-controller="Course" asp-action="Remove" asp-route-courseId="@Model.CourseId" class="flex-shrink-0 btn btn-sm btn-primary px-3 border-end" style="border-radius: 30px 0 0 30px;">Delete Course</a>
            }

        </div>
    </div>
</div>

LMSWeb/Views/Course/Edit.cshtml
@model Course

@{
    ViewData["Title"] = "Course Contents";
}

<div class="container">
<div class="row">
    <div class="col-md-3">
        <input type="hidden" id="userRole" value="@User.Claims.FirstOrDefault(c => c.Type == "role")?.Value" />
        <input type="hidden" id="userId" value="@User.Claims.FirstOrDefault(c => c.Type == "id")?.Value" />
        <input type="hidden" id="instId" value="@Model.UserId" />
        <input type="hidden" id="courseId" value="@Model.CourseId" />
        <input type="hidden" id="isEnrolled" value="@Model.Enrollments.Any(e => e.CourseId == Model.CourseId && e.UserId == (Convert.ToInt32(@User.Claims.FirstOrDefault(c => c.Type == "id")?.Value))).ToString()" />
        <!-- Display Lesson titles as links -->
        <div class="mb-4">
            <h4 class="mb-3">Lesson Titles</h4>
            <ul class="list-group">
                @foreach (var lesson in Model.Lessons)
                {
                    <li class="list-group-item">
                        <a href="#" data-lessonid="@lesson.LessonId" onclick="updateLessonContent('@lesson.LessonId')">@lesson.Title</a>
                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (lesson.UserLessonProgresses.Any(ulp => ulp.UserId == Convert.ToInt32(User.Claims.FirstOrDefault(c => c.Type == "id").Value) && ulp.IsCompleted))
                            {
                                <i class="bi bi-check-circle-fill justify-content-end"></i>
                            }
                            else if (lesson.UserLessonProgresses.Any(ulp => ulp.UserId == Convert.ToInt32(User.Claims.FirstOrDefault(c => c.Type == "id").Value) && !ulp.IsCompleted))
                            {
                                <i class="bi bi-check-circle justify-content-end"></i>
                            }
                        }
                        @if ((User.Identity.IsAuthenticated) && (((((User.Claims.FirstOrDefault(c => c.Type == "role").Value.Equals("Instructor")))) && ((Convert.ToInt32(User.Claims.FirstOrDefault(c => c.Type == "id").Value)) == Model.UserId)) ||
                       User.Claims.FirstOrDefault(c => c.Type == "role").Value.Equals("Admin")))
                        {
                            <a asp-controller="Lesson" asp-action="Delete" asp-route-lessonId="@lesson.LessonId"><i class="bi bi-trash-fill justify-content-end"></i></a>
                        }
                    </li>
                }
            </ul>
        </div>
        <!-- Button to add a new lesson -->
        @if ((User.Identity.IsAuthenticated) && (((((User.Claims.FirstOrDefault(c => c.Type == "role").Value.Equals("Instructor")))) && ((Convert.ToInt32(User.Claims.FirstOrDefault(c => c.Type == "id").Value)) == Model.UserId)) ||
        User.Claims.FirstOrDefault(c => c.Type == "role").Value.Equals("Admin")))
        {
            <div class="mb-4">
                <a asp-controller="Lesson" asp-action="Upsert" asp-route-courseId="@Model.CourseId" class="btn btn-success btn-block">Add New Lesson</a>
            </div>
        }

    </div>
    <div class="col-md-9">
        <!-- Display Lesson content here -->
        <div id="lessonContent">
            <!-- Content for the selected Lesson will be loaded here -->
        </div>

        <input type="hidden" id="hiddenLessonId" value="" />
    </div>
</div>
</div>

@section scripts1 {
    <script>
        var userRole = $("#userRole").val();
        var userId = $("#userId").val();
        var instId = $("#instId").val();
        var courseId = $("#courseId").val();
        var isEnrolled = $("#isEnrolled").val();
        console.log(isEnrolled)//del
        // Function to update the lesson content when a title is clicked
        function updateLessonContent(lessonId) {
            var hiddenLessonId = document.getElementById('hiddenLessonId');
            hiddenLessonId.value = lessonId;

            // Send an AJAX request to the server to fetch the lesson
            $.ajax({
                url: '/Lesson/GetLesson', // Replace with the actual URL and controller action
                type: 'GET',
                data: { lessonId: lessonId },
                success: function (data) {
                    if (data) {
                        // Update the lessonContent div with the retrieved lesson data
                        var lessonContentDiv = document.getElementById('lessonContent');
                        lessonContentDiv.innerHTML = '';

                        // Create and append the lesson title
                        var lessonTitle = document.createElement('h4');
                        lessonTitle.textContent = data.Title;
                        lessonContentDiv.appendChild(lessonTitle);

                        // Create and append the contents as an unordered list
                        if (data.Contents && data.Contents.$values.length > 0) {
                            var contentList = document.createElement('ul');
                            data.Contents.$values.forEach(function (content) {
                                var contentItem = document.createElement('li');
                                // Check the content type and create the appropriate element
                                switch (content.ContentType) {
                                    case 0: // Text
                                        var textContent = document.createElement('div');
                                        textContent.textContent = content.ContentText;
                                        contentItem.appendChild(textContent);
                                        break;
                                    case 1: // Image
                                        var imageContent = document.createElement('div');
                                        var imageElement = document.createElement('img');
                                        imageElement.src = content.ImageUrl;
                                        imageElement.alt = 'Image';
                                        imageContent.appendChild(imageElement);
                                        contentItem.appendChild(imageContent);
                                        break;
                                    case 2: // Video
                                        var videoContent = document.createElement('div');
                                        var videoElement = document.createElement('iframe');
                                        var videoUrl = content.VideoUrl;
                                        if (videoUrl.includes("youtube.com")) {
                                            var videoId = videoUrl.split('v=')[1];
                                            var embedUrl = 'https://www.youtube.com/embed/' + videoId;
                                            videoElement.src = embedUrl;
                                            videoElement.width = '560';
                                            videoElement.height = '315';
                                            videoElement.frameborder = '0';
                                            videoElement.allowfullscreen = true;
                                            videoContent.appendChild(videoElement);
                                            contentItem.appendChild(videoContent);
                                        }
                                        break;
                                    default:
                                        // Handle other content types here
                                        break;
                                }
                                contentList.appendChild(contentItem);
                            });
                            lessonContentDiv.appendChild(contentList);
                        }
                        if ((userRole === "Admin") || ((userRole === "Instructor") && (userId === instId))) {
                            // Generate the "Add New Content" button for the selected lesson
                            var addContentButton = document.createElement('button');
                            addContentButton.className = 'btn btn-primary';
                            addContentButton.textContent = 'Add New Content';

                            addContentButton.onclick = function () {
                                // Redirect to the content creation page with the selected lesson ID
                                window.location.href = '/Content/Upsert?lessonId=' + data.LessonId;
                            };
                            lessonContentDiv.appendChild(addContentButton);
                        }
                        if (isEnrolled === "True") {
                            var lessonProgress = data.UserLessonProgresses.$values;
                            if (lessonProgress[0].IsCompleted === false) {
                                var completeButton = document.createElement('button');
                                completeButton.className = 'btn btn-success';
                                completeButton.textContent = 'Complete';
                                completeButton.onclick = function () {
                                    // Send an AJAX request to mark the lesson as completed
                                    $.ajax({
                                        url: '/Lesson/CompleteLesson', // Replace with the actual URL and controller action
                                        type: 'POST',
                                        data: { lessonId: data.LessonId },
                                        success: function () {
                                            // Reload the content to show the completion status
                                            var url = '/Course/Edit?courseId=' + courseId;
                                            window.location.href = url;
                                        },
                                        error: function (error) {
                                            console.error(error);
                                        }
                                    });
                                };
                                lessonContentDiv.appendChild(completeButton);
                            }
                        }
                    }
                },
                error: function (error) {
                    console.error(error);
                }
            });
        }
    </script>
}

LMSWeb/Views/Course/EnrolledUsers.cshtml
<table class="table table-info">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
            <tr>
                <td>@user.Name</td>
                <td>@user.Email</td>
            </tr>
        }
    </tbody>
</table>

LMSWeb/Views/Course/Index.cshtml
@model IEnumerable<Course>

<!-- Courses Start -->
<div class="container-xxl py-5">
    <div class="container">
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
            <h6 class="section-title bg-white text-center text-primary px-3">Courses</h6>

            <div class="col-md-9 mb-4">
                <div class="d-flex justify-content-between align-items-center">
                    <form method="GET" asp-controller="Course" asp-action="Search" class="form-inline col-6">
                        <div class="input-group">
                            <input type="text" name="search" placeholder="Search by Title" class="form-control" />
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-primary">Search</button>
                            </div>
                        </div>
                    </form>
                    @if ((User.Claims.FirstOrDefault(c => c.Type == "role")?.Value.Equals("Instructor") ?? false) ||
                    (User.Claims.FirstOrDefault(c => c.Type == "role")?.Value.Equals("Admin") ?? false))
                    {
                        <a asp-controller="Course" asp-action="Upsert" class="btn btn-primary">
                            Create Course
                        </a>
                    }
                </div>
            </div>
        </div>
        <div class="row g-4 justify-content-center">
            <div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                @foreach (Course course in Model)
                {
                    <div class="course-item bg-light">
                        <div class="position-relative overflow-hidden">
                            <img class="img-fluid" src="@course.ImageUrl" alt="">
                            <div class="w-100 d-flex justify-content-center position-absolute bottom-0 start-0 mb-4">
                                <a asp-action="Details" asp-route-courseId="@course.CourseId" class="flex-shrink-0 btn btn-sm btn-primary px-3 border-end" style="border-radius: 30px 30px 30px 30px;">Goes to details</a>

                            </div>
                        </div>
                        <div class="text-center p-4 pb-0">
                           @*  <h3 class="mb-0">Bu ve altini kaldiralim</h3> *@
                            <div class="mb-3">
                                <small class="fa fa-star text-primary"></small>
                                <small class="fa fa-star text-primary"></small>
                                <small class="fa fa-star text-primary"></small>
                                <small class="fa fa-star text-primary"></small>
                                <small class="fa fa-star text-primary"></small>
                                <small>(123)</small>
                            </div>
                            <h5 class="mb-4">@course.Title</h5>
                        </div>
                        <div class="d-flex border-top">
                            <small class="flex-fill text-center border-end py-2"><i class="fa fa-user-tie text-primary me-2"></i>@course.User.Name</small>
                           @*  <small class="flex-fill text-center border-end py-2"><i class="fa fa-clock text-primary me-2"></i>Kaldiralim</small> *@
                            <small class="flex-fill text-center py-2"><i class="fa fa-user text-primary me-2"></i>@course.EnrollmentCount Students</small>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
    <!-- Courses End -->

LMSWeb/Views/Course/Upsert.cshtml
@model CourseVM

<div class="card shadow border-0 my-4">
    <div class="card-header bg-secondary bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2"> @(Model.Course.CourseId != 0 ? "Update" : "Create") Course</h2>
            </div>
        </div>
    </div>

    <div class="card-body p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <input asp-for="Course.CourseId" hidden />
            <input asp-for="Course.ImageUrl" hidden />
            <div class="row">
                <div class="col-10">
                    <div class="border p-3">
                        @*<div asp-validation-summary="ModelOnly"></div>*@
                        <!-- Manually assign the UserId property -->
                        <input asp-for="Course.UserId" value="@Convert.ToInt32(User.Claims.FirstOrDefault(c => c.Type == "id").Value)" hidden />
                        <input asp-for="Course.EnrollmentCount" value="0" hidden />
                        <div class="form-floating py-2 col-12">
                            <input asp-for="Course.Title" class="form-control border-0 shadow" />
                            <label asp-for="Course.Title" class="ms-2"></label>
                            <span asp-validation-for="Course.Title" class="text-danger"></span>
                        </div>
                        <div class="py-2 col-12">
                            <label asp-for="Course.Description" class="ms-2 text-muted"></label>
                            <textarea asp-for="Course.Description" class="form-control border-0 shadow"></textarea>
                        </div>

                        <div class="form-floating py-2 col-12">
                            <input type="file" name="file" class="form-control border-0 shadow" />
                            <label asp-for="Course.ImageUrl" class="ms-2"></label>
                        </div>
                        <div class="row pt-2">
                            <div class="col-6 col-md-3">
                                @if (Model.Course.CourseId != 0)
                                {
                                    <button type="submit" class="btn btn-primary form-control">Update</button>
                                }
                                else
                                {
                                    <button type="submit" class="btn btn-primary form-control">Create</button>
                                }
                            </div>
                            <div class="col-6 col-md-3">
                                <a asp-controller="Course" asp-action="Index" class="btn btn-outline-primary border  form-control">
                                    Back to List
                                </a>
                            </div>
                        </div>


                    </div>
                </div>
                <div class="col-2">
                    <img src="@Model.Course.ImageUrl" width="100%"
                         style="border-radius:5px; border:1px solid #bbb9b9" />
                </div>
            </div>

        </form>
    </div>
</div>